### ISSUE TITLE
The OpenAI module cannot be imported.

### ISSUE THREAD

**Issue by PlumpMole** [RyanFeiluX/langchain_moonshot#1]
![image](https://github.com/RyanFeiluX/langchain_moonshot/assets/87522076/fe492d68-8ec1-4e09-91b6-3dc799d927f3)

**Comment by RyanFeiluX** [comment]
Sorry for late reply.
The lib does not export OpenAPI class but ChatOpenAI. Please refer to the [example ](https://github.com/RyanFeiluX/langchain_moonshot/blob/main/langchain-moonshot-kaggle.ipynb)
